%YAML:1.0

#common parameters
imu_topic: "/imu"
event_left_topic: "/left_event"
event_right_topic: "/right_event"
image_left_topic: "/left_camera"
image_right_topic: "/right_camera"


system_mode: 1 # 0 for ESIO, 1 for ESVIO

output_path: "/home/cpy/Datasets/output"

###########################################################################################################################

#camera calibration
cam_left_calib: "cam0_esvio.yaml"
cam_right_calib: "cam1_esvio.yaml"

#event calibration
event_left_calib: "event0_esvio.yaml"
event_right_calib: "event1_esvio.yaml"

image_width: 1280
image_height: 800

event_width: 1280
event_height: 720


###########################################################################################################################
# Transformation between imu and left cam/event

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 0   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.
#If you choose 0 or 1, you should write down the following matrix.

#Rotation from left camera frame to imu frame, imu^R_cam; 
extrinsicRotation: !!opencv-matrix 
   rows: 3
   cols: 3
   dt: d

   data: [-0.999996, -0.001231, 0.002471,
          -0.001210, 0.999964, 0.008450,
          -0.002481, 0.008447, -0.999961]

extrinsicTranslation: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d

   data: [0.093916, -0.013018, -0.009592]

#### Rotation from left event frame to imu frame, imu^R_event; 
extrinsicRotation_event: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d

   data: [-0.999954, 0.009573, 0.001124,
          0.009578, 0.999943, 0.004676,
          -0.001079, 0.004686, -0.999988]

extrinsicTranslation_event: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d

   data: [0.094000, 0.057194, -0.014334]

T_camera_imu: 0  # whether the input is imu to cam. if yes, T_camera_imu = 1 
T_event_imu: 0  # whether the input is imu to event. if yes, T_camera_imu = 1 

###########################################################################################################################
# Transformation between right and left camera, left to right
Rrl: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.999982, 0.000447, 0.005921,
         -0.000450, 1.000000, 0.000391,
         -0.005921, -0.000393, 0.999982] 

Trl: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.119892, -0.001417, 0.000785]

body_T_cam1: !!opencv-matrix # camera right camera to imu
   rows: 4
   cols: 4
   dt: d
   data: [-0.999964, -0.000780, 0.008392, -0.025979,
         -0.000712, 0.999967, 0.008064, -0.011692,
         -0.008398, 0.008058, -0.999932, -0.009803,
         0.000000, 0.000000, 0.000000, 1.000000]

###########################################################################################################################
# left event to right event. Rrl_event = (R_l_re)^-1 * R_l_le
Rrl_event: !!opencv-matrix
   rows: 3
   cols: 3
   dt: d
   data: [0.999993, -0.000648, -0.003651,
          0.000637, 0.999995, -0.003002,
          0.003653, 0.003000, 0.999989]

Trl_event: !!opencv-matrix
   rows: 3
   cols: 1
   dt: d
   data: [-0.120113, 0.000879, -0.000283]

body_T_event1: !!opencv-matrix # right event to imu.  R_i_re = (R_l_i)^-1 * R_l_re
   rows: 4
   cols: 4
   dt: d
   data: [-0.999957, 0.008932, -0.002500, -0.026117,
          0.008913, 0.999931, 0.007710, 0.057388,
          0.002569, 0.007688, -0.999967, -0.014315,
          0.000000, 0.000000, 0.000000, 1.000000]

###########################################################################################################################
#time surface map
ignore_polarity: 0 #true 1 false 0;
decay_ms: 20 #20
median_blur_kernel_size: 0 #1 or 0
feature_filter_threshold: 0.01

#feature traker paprameters
TS_LK_threshold: 128.0   # the feature detection is based on the time surface
max_cnt: 150 #250 #300 #150            # max feature number in feature tracking event 
max_cnt_img: 150                       # max feature number in feature tracking image
min_dist: 10 #10            # min distance between two event features 
min_dist_img: 10            # min distance between two image features 
freq: 15 # ESVIO 15  ESIO 10             # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image 
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
flow_back: 1            # perform forward and backward optical flow to improve feature tracking accuracy
equalize: 0             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points
Num_of_thread: 4        #number of the threads for the big event data process

Do_motion_correction: 0 #whether use motion correction

###########################################################################################################################
#optimization parameters
max_solver_time: 0.04  # max solver itration time (ms), to guarantee real time
max_num_iterations: 8   # max solver itrations, to guarantee real time
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)

###########################################################################################################################
acc_n: 0.2 # accelerometer measurement noise standard deviation. #0.2   0.04
gyr_n: 0.05 # gyroscope measurement noise standard deviation.     #0.05  0.004
acc_w: 0.002 #0.001 #0.002 #8.0169405615955990e-04 #0.001 #0.002 #8.0169405615955990e-04        # accelerometer bias random work noise standard deviation.  #0.002
gyr_w: 4.0e-5 #0.0001 #4.0e-5 #2.8618210492185127e-05 #2.0e-5 #4.0e-5 #2.8618210492185127e-05       # gyroscope bias random work noise standard deviation.     #4.0e-5
g_norm: 9.80766     # gravity magnitude

###########################################################################################################################

#unsynchronization parameters
estimate_td: 1                      # online estimate time offset between camera and imu
td: 0.0    #0.0            # initial value of time offset. unit: s. readed image clock + td = real image clock (IMU clock)

#rolling shutter parameters
rolling_shutter: 0                  # 0: global shutter camera, 1: rolling shutter camera
rolling_shutter_tr: 0               # unit: s. rolling shutter read out time per frame (from data sheet).

###########################################################################################################################

#loop closure parameters
loop_closure: 1                    # start loop closure
loop_closure_topic: "/left_camera"   
load_previous_pose_graph: 0 #1        # load and reuse previous pose graph; load from 'pose_graph_save_path'
fast_relocalization: 0             # useful in real-time and large project

#visualization parameters
save_image: 1                   #  (DEBUG_IMAGE)  
visualize_imu_forward: 1        # output imu forward propogation to achieve low latency and high frequence results
visualize_camera_size: 0.4      # size of camera marker in RVIZ
save_loop_match: 0              # 
